---
vx:
  "a_k":
    file: "ka-ka.wav"
    pitch: "C3"
    color: null
    start_point: 10.03
    end_point: 14.52
  "a_-":
    file: "a.wav"
    pitch: "C3"
    color: null
    start_point: 0.0
    end_point: 0.0
  "a_i":
    file: "a-i.wav"
    pitch: "C3"
    color: null
    start_point: 0.0
    end_point: 0.0
  "i_-":
    file: "i.wav"
    pitch: "C3"
    color: null
    start_point: 0.0
    end_point: 0.0
cv:
  "-a":
    file: "a.wav"
    pitch: "C3"
    color: null
    start_point: 0.0
    note_point: 0.0
    stable_start_point: 0.0
    stable_end_point: 0.0
  "ka":
    file: "ka-ka.wav"
    pitch: "C3"
    color: null
    connection_point: 11.88
    note_point: 15.23
    stable_start_point: 22.45
    stable_end_point: 62.02
v:
  "a":
    file: "a.wav"
    pitch: "C3"
    color: null
    start_point: 20.03
    end_point: 0.0
  "i":
    file: "i.wav"
    pitch: "C3"
    color: null
    start_point: 0.0
    end_point: 0.0
vxv:
  "a_s_a":
    file: "sa-sa.wav"
    pitch: "C3"
    color: null
    start_point: 15.44
    note_point: 23.84
    end_point: 40.50
other:
